import { logger } from '../lib/logger';
import { Customer } from '../models/Customer';

export interface AudienceFilters {
  minTotalSpent?: number;
  maxTotalSpent?: number;
  cities?: string[];
  genders?: string[];
  minAge?: number;
  maxAge?: number;
  lastPurchaseBefore?: string;
  lastPurchaseAfter?: string;
  orderCategories?: string[];
  minOrderCount?: number;
  maxOrderCount?: number;
}

export function buildWhereClause(filters: any): any {
  let parsedFilters: AudienceFilters = {};
  if (typeof filters === 'string') {
    try {
      parsedFilters = JSON.parse(filters);
    } catch {
      parsedFilters = {};
    }
  } else {
    parsedFilters = filters || {};
  }

  const where: any = {};
  if (parsedFilters.minTotalSpent) {
    where.totalSpent = { $gte: parsedFilters.minTotalSpent };
  }
  return where;
}

export async function generateAudience(query: string) {
  logger.info({ query }, 'MOCK AI: Generating audience');
  
  return {
    name: "Mocked Audience",
    description: "Generated by Mock AI without OpenAI API Key",
    filters: JSON.stringify({ minTotalSpent: 500 }),
    reasoning: "Since the OpenAI API key is missing, this is a mock audience.",
    estimatedCount: await Customer.countDocuments()
  };
}

export async function generateCampaign(goal: string, audienceContext?: any) {
  logger.info({ goal }, 'MOCK AI: Generating campaign');
  
  return {
    title: "Mocked AI Campaign",
    offer: "20% off",
    message: "Hey {{name}}, here is a mock message because OpenAI API key is not configured!",
    cta: "Buy Now",
    channel: "WHATSAPP",
    audienceReasoning: "Mock reasoning",
    messageReasoning: "Mock reasoning",
    channelReasoning: "Mock reasoning",
    offerReasoning: "Mock reasoning",
    predictedMetrics: JSON.stringify({
      deliveryRate: 0.9,
      openRate: 0.6,
      ctr: 0.2,
      conversionRate: 0.05
    })
  };
}

export async function autonomousCampaignAgent(goal: string) {
  logger.info({ goal }, 'Autonomous agent started (MOCKED)');
  const audience = await generateAudience(goal);
  const campaign = await generateCampaign(goal, audience);
  return { audience, campaign };
}

export async function generateInsights(campaignId: string) {
  logger.info({ campaignId }, 'Generating insights (MOCKED)');
  return {
    insights: [
      {
        insight: "Mocked Insight: Your open rates look okay.",
        category: "general",
        severity: "info",
        recommendation: "Please configure an OpenAI API key for real insights."
      }
    ],
    nextCampaignSuggestion: "Mock follow-up campaign."
  };
}
