"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildWhereClause = buildWhereClause;
exports.generateAudience = generateAudience;
exports.generateCampaign = generateCampaign;
exports.autonomousCampaignAgent = autonomousCampaignAgent;
exports.generateInsights = generateInsights;
const logger_1 = require("../lib/logger");
const Customer_1 = require("../models/Customer");
function buildWhereClause(filters) {
    let parsedFilters = {};
    if (typeof filters === 'string') {
        try {
            parsedFilters = JSON.parse(filters);
        }
        catch {
            parsedFilters = {};
        }
    }
    else {
        parsedFilters = filters || {};
    }
    const where = {};
    if (parsedFilters.minTotalSpent) {
        where.totalSpent = { $gte: parsedFilters.minTotalSpent };
    }
    return where;
}
async function generateAudience(query) {
    logger_1.logger.info({ query }, 'MOCK AI: Generating audience');
    return {
        name: "Mocked Audience",
        description: "Generated by Mock AI without OpenAI API Key",
        filters: JSON.stringify({ minTotalSpent: 500 }),
        reasoning: "Since the OpenAI API key is missing, this is a mock audience.",
        estimatedCount: await Customer_1.Customer.countDocuments()
    };
}
async function generateCampaign(goal, audienceContext) {
    logger_1.logger.info({ goal }, 'MOCK AI: Generating campaign');
    return {
        title: "Mocked AI Campaign",
        offer: "20% off",
        message: "Hey {{name}}, here is a mock message because OpenAI API key is not configured!",
        cta: "Buy Now",
        channel: "WHATSAPP",
        audienceReasoning: "Mock reasoning",
        messageReasoning: "Mock reasoning",
        channelReasoning: "Mock reasoning",
        offerReasoning: "Mock reasoning",
        predictedMetrics: JSON.stringify({
            deliveryRate: 0.9,
            openRate: 0.6,
            ctr: 0.2,
            conversionRate: 0.05
        })
    };
}
async function autonomousCampaignAgent(goal) {
    logger_1.logger.info({ goal }, 'Autonomous agent started (MOCKED)');
    const audience = await generateAudience(goal);
    const campaign = await generateCampaign(goal, audience);
    return { audience, campaign };
}
async function generateInsights(campaignId) {
    logger_1.logger.info({ campaignId }, 'Generating insights (MOCKED)');
    return {
        insights: [
            {
                insight: "Mocked Insight: Your open rates look okay.",
                category: "general",
                severity: "info",
                recommendation: "Please configure an OpenAI API key for real insights."
            }
        ],
        nextCampaignSuggestion: "Mock follow-up campaign."
    };
}
//# sourceMappingURL=ai.service.js.map